# # specify the node base image with your desired version node:<version>
# FROM node:10
# RUN mkdir /server
# ADD . /server
# WORKDIR /server
# RUN npm install

# # replace this with your application's default port
# EXPOSE 3000
# CMD ["node", "server"]