DROP TABLE IF EXISTS products;
CREATE TABLE IF NOT EXISTS products (
    ID INT PRIMARY KEY,
    NAME VARCHAR (100) NOT NULL,
    SLOGAN VARCHAR (1000),
    DESCRIPTION VARCHAR (1000),
    CATEGORY VARCHAR (100) NOT NULL,
    DEFAULT_PRICE INT,
    FEATURES TEXT[],
    RELATED INT[]
);