DROP TABLE IF EXISTS photos;
DROP TABLE IF EXISTS tempPhotos;
DROP TABLE IF EXISTS skus;
DROP TABLE IF EXISTS features;
DROP TABLE IF EXISTS styles;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS related;
CREATE TABLE products (
    ID INT PRIMARY KEY,
    NAME VARCHAR (100) NOT NULL,
    SLOGAN VARCHAR (1000),
    DESCRIPTION VARCHAR (1000),
    CATEGORY VARCHAR (100) NOT NULL,
    DEFAULT_PRICE VARCHAR (100)
);


CREATE TABLE styles (
    ID INTEGER PRIMARY KEY,
    PRODUCT_ID INTEGER,
    NAME VARCHAR (100) NOT NULL,
    SALE_PRICE VARCHAR (100),
    ORIGINAL_PRICE VARCHAR (100),
    DEFAULT_ITEM INTEGER,
    FOREIGN KEY (PRODUCT_ID) REFERENCES products(ID)
);


CREATE TABLE features (
    ID INTEGER PRIMARY KEY,
    PRODUCT_ID INTEGER,
    FEATURE VARCHAR (1000),
    VALUE VARCHAR (1000),
    FOREIGN KEY (PRODUCT_ID) REFERENCES products(ID)
);

CREATE TABLE skus (
    ID INTEGER PRIMARY KEY,
    STYLE_ID INTEGER,
    SIZE VARCHAR (10),
    QUANTITY VARCHAR (1000),
    FOREIGN KEY (STYLE_ID) REFERENCES styles(ID)
);


CREATE TABLE tempPhotos (
    ID INTEGER,
    STYLE_ID INTEGER,
    THUMBNAIL_URL VARCHAR (100000),
    URL VARCHAR (100000)
);

CREATE TABLE photos (
    ID INTEGER PRIMARY KEY,
    STYLE_ID INTEGER,
    THUMBNAIL_URL VARCHAR (100000),
    URL VARCHAR (100000),
    FOREIGN KEY (STYLE_ID) REFERENCES styles(ID)
);

CREATE TABLE related (
    ID INTEGER PRIMARY KEY,
    CURRENT_PRODUCT_ID INTEGER,
    RELATED_PRODUCT_ID INTEGER
);


